import { Cited, Sources } from "../../components";
import { useProject } from "./context";
import { Locked } from "./Locked";
import { TEMPLATE_INFO } from "./PlanPage";

/** Everything in one printable page. "Save as PDF" uses the browser's print dialog. */
export default function ReportPage() {
  const { project, results } = useProject();
  const { research: r, validate: v, plan: p, build: b } = results;
  if (!r) return <Locked need="Research" to="../research" />;
  const src = r.sources;

  return (
    <article className="report">
      <div className="row noprint" style={{ justifyContent: "space-between" }}>
        <p className="muted">A single document with everything Nirmaan found and planned. Use it for your synopsis, viva or a mentor.</p>
        <button className="btn btn--build" onClick={() => window.print()}>Save as PDF</button>
      </div>

      <header className="report__head">
        <h1>{project.name}</h1>
        <p className="lede">{project.idea}</p>
        <p className="muted">Generated by Nirmaan on {new Date().toLocaleDateString()}</p>
      </header>

      <section>
        <h2>1. Market research</h2>
        <p><Cited text={r.summary} sources={src} /></p>
        <p><strong>Trend.</strong> <Cited text={r.market_trend} sources={src} /></p>
        {r.market_size && <p><strong>Market size.</strong> <Cited text={r.market_size} sources={src} /></p>}
        {(r.key_numbers?.length ?? 0) > 0 && (
          <ul>{r.key_numbers!.map((n) => <li key={n.label}><strong>{n.value}</strong>: {n.label}{n.source && <Cited text={` [${n.source}]`} sources={src} />}</li>)}</ul>
        )}
        <h3>Competitors</h3>
        <table>
          <thead><tr><th>Product</th><th>What they do</th><th>Pricing</th><th>Gap</th></tr></thead>
          <tbody>{r.competitors.map((c) => <tr key={c.name}><td>{c.name}</td><td><Cited text={c.what_they_do} sources={src} /></td><td><Cited text={c.pricing ?? "Not found"} sources={src} /></td><td><Cited text={c.weakness} sources={src} /></td></tr>)}</tbody>
        </table>
        <h3>User complaints</h3>
        <ul>{r.user_complaints.map((x) => <li key={x}><Cited text={x} sources={src} /></li>)}</ul>
        <h3>Opportunities</h3>
        <ul>{r.opportunities.map((x) => <li key={x}><Cited text={x} sources={src} /></li>)}</ul>
        {r.india_angle && <><h3>India angle</h3><p><Cited text={r.india_angle} sources={src} /></p></>}
        {r.swot && (
          <>
            <h3>SWOT</h3>
            <table>
              <tbody>
                <tr><th>Strengths</th><td>{r.swot.strengths.join("; ")}</td></tr>
                <tr><th>Weaknesses</th><td>{r.swot.weaknesses.join("; ")}</td></tr>
                <tr><th>Opportunities</th><td>{r.swot.opportunities.join("; ")}</td></tr>
                <tr><th>Threats</th><td>{r.swot.threats.join("; ")}</td></tr>
              </tbody>
            </table>
          </>
        )}
      </section>

      {v && (
        <section>
          <h2>2. Validation</h2>
          <p><strong>Verdict: {v.verdict}</strong> (feasibility {v.feasibility_score}/10). {v.verdict_reason}</p>
          <p><strong>Target user:</strong> {v.target_user}</p>
          <p><strong>Problem:</strong> {v.problem_statement}</p>
          <p><strong>Unique angle:</strong> {v.unique_angle}</p>
          <h3>Risks</h3>
          <ul>{v.risks.map((x) => <li key={x}>{x}</li>)}</ul>
        </section>
      )}

      {p && (
        <section>
          <h2>3. Plan</h2>
          <table>
            <thead><tr><th>Feature</th><th>Priority</th><th>Description</th></tr></thead>
            <tbody>{p.features.map((f) => <tr key={f.name}><td>{f.name}{b?.selected_features.includes(f.name) ? " (selected)" : ""}</td><td>{f.priority}</td><td>{f.description}</td></tr>)}</tbody>
          </table>
          <h3>Tech stack</h3>
          <ul>{p.tech_stack.map((t) => <li key={t.layer}><strong>{t.layer}:</strong> {t.choice}. {t.why}</li>)}</ul>
          <h3>How it works</h3>
          <p>{p.beginner_explanation}</p>
          <h3>Viva questions</h3>
          {p.viva_questions.map((q, i) => <div key={q.question} className="qa"><p><strong>Q{i + 1}. {q.question}</strong></p><p>{q.answer}</p></div>)}
        </section>
      )}

      {b && (
        <section>
          <h2>4. Starter project</h2>
          <p><strong>{b.config.app_name}</strong>: {b.config.tagline}. Type: {TEMPLATE_INFO[b.template].title}.</p>
          {b.checks && <p>Quality checks: {b.checks.passed} of {b.checks.total} passed, {b.checks.files.length} files, {b.checks.total_lines} lines.</p>}
        </section>
      )}

      <section><Sources sources={src} /></section>
    </article>
  );
}
